import os

DEBUG = False
SQLALCHEMY_ECHO = False
SQLALCHEMY_DATABASE_URI = os.environ['DATABASE_URL']
AWS_ACCESS_KEY_ID = os.environ['IAMDAVEHAWKINS_AWS_KEY_ID']
AWS_SECRET_ACCESS_KEY = os.environ['IAMDAVEHAWKINS_AWS_SECRET']
