"""empty message

Revision ID: 166e6e2fa50d
Revises: 1149c3641a75
Create Date: 2015-05-31 16:16:05.146881

"""

# revision identifiers, used by Alembic.
revision = '166e6e2fa50d'
down_revision = '1149c3641a75'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parttypes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('min_per_bike', sa.Integer(), nullable=True),
    sa.Column('max_per_bike', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('weight_g', sa.Float(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('img_path', sa.String(), nullable=True),
    sa.Column('retired', sa.Integer(), nullable=True),
    sa.Column('parttype_id', sa.Integer(), nullable=True),
    sa.Column('bike_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bike_id'], ['bikes.id'], ),
    sa.ForeignKeyConstraint(['parttype_id'], ['parttypes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'bikes', sa.Column('img_path', sa.String(), nullable=True))
    op.add_column(u'bikes', sa.Column('retired', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'bikes', 'retired')
    op.drop_column(u'bikes', 'img_path')
    op.drop_table('parts')
    op.drop_table('parttypes')
    ### end Alembic commands ###
